# Server details
server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api

# Spring configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_management
    username: root
    password: rgit@1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  profiles:
    active: local
  application:
    name: order-management
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orderProducer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: orderTransaction
    consumer:
      bootstrap-servers: localhost:9092
      client-id: orderConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      isolationLevel: read_committed
      max-poll-records: 7
      heartbeat-interval: 6000

kafka:
  topic:
    order:
      name: order-topic
      groupId: order-group

