server:
  servlet:
    context-path: /api

# Actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: all

# Spring configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_mgmt?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  profiles:
    active: local
  application:
    name: order-management
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orderManagementProducer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: orderTransaction
    consumer:
      bootstrap-servers: localhost:9092
      client-id: orderManagementConsumer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      isolationLevel: read_committed
      max-poll-records: 10
      heartbeat-interval: 6000

kafka:
  topic:
    order:
      name: order-management-topic
      groupId: order-management-group