server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api

# Spring configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Orders?useSSL=false
    username: root
    password: danton25
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  profiles:
    active: local
  application:
    name: order-management
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orderProducer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: orderTransaction
    consumer:
      bootstrap-servers: localhost:9092
      client-id: orderConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      isolationLevel: read_committed
      max-poll-records: 5
      heartbeat-interval: 6000

kafka:
  topic:
    order:
      name: order-Management
      groupId: order-group1