package org.example.response;

public enum StatusMessage {
    SUCCESS,
    UNKNOWN_INTERNAL_ERROR,
    MISSING_REQUEST_PARAMETER,
    TOTES_SERVICE_INTERNAL_ERROR,
    EQUIPMENT_SERVICE_INTERNAL_ERROR
}
