server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: local

  application:
    name: OrderManagement

  datasource:
    url: jdbc:mysql://localhost:3306/ordermanagement?useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: OrderClient
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: OrderTransId
    consumer:
      bootstrap-servers: localhost:9092
      client-id: OrderClient
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      isolation-level: read_committed
      max-poll-records: 10
      heartbeat-interval: 6000

kafka:
    topic:
      name: OrderManagementTopic
      groupId: OrderManagementGroup